# Generated by Django 4.0.4 on 2022-05-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('profit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_num', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('contract_date', models.DateField()),
                ('contract_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100, null=True)),
                ('industry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('number', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('sales_volume', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('supply_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.center')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('estimate_delivery_date', models.DateField()),
                ('lodgement_delivery_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.contract')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.models')),
                ('salesman_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.staff')),
            ],
            options={
                'ordering': ['salesman_num__number', 'estimate_delivery_date', 'product_model__model'],
            },
        ),
        migrations.AddConstraint(
            model_name='models',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='unit_price_gte_0'),
        ),
        migrations.AddField(
            model_name='model_center',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.center'),
        ),
        migrations.AddField(
            model_name='model_center',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.models'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='supply_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.center'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.staff'),
        ),
        migrations.AddField(
            model_name='contract',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.enterprise'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 0)), name='age_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='quantity_gte_0_order'),
        ),
        migrations.AddConstraint(
            model_name='model_center',
            constraint=models.UniqueConstraint(fields=('model', 'center'), name='unique_mc'),
        ),
        migrations.AddConstraint(
            model_name='model_center',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='quantity_gte_0_model_center'),
        ),
    ]
